### ISSUE TITLE
Missing slash in generated url for actions

### ISSUE THREAD

**Issue by MscrmTools** [DynamicsNinja/InAppNotificationBuilder#4]
The code generated for Power Automate has an issue when building the url for the action to perform. There is a missing Slash

![image](https://user-images.githubusercontent.com/10774317/164011422-40153106-23f7-4765-9730-ff37243d9df3.png)

---
- Deployment: Online
- DB Version: 9.2.22033.152
- Connection Controls Version: 1.2022.4.48
- XrmToolBox Version: 1.2022.2.54
- Tool Version: 1.2021.12.1

**Comment by DynamicsNinja** [comment]
I tried to reproduce it on a few organizations but didn't have the issue above. It's probably related to ConnectionDetail.**WebApplicationUrl** that I'm using for the base URL (which has / in the end in my case). 

Is it maybe better to put ConnectionDetail.**OriginalUrl** instead and add / at the end since it is the same but without the ending slash?

**Comment by MscrmTools** [comment]
I guess the best is to test if the url ends with a slash and add it if it is missing

**Comment by DynamicsNinja** [comment]
Good point, I'll make it that way.
